name: nhealth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  provider: ^3.0.0
  image_picker: ^0.6.2+1
  sqflite: ^1.2.0
  uuid: ^2.0.4
  fluttertoast: ^3.1.3
  intl: ^0.16.1
  search_widget: ^1.0.1
  basic_utils: ^2.4.8
  datetime_picker_formfield: ^1.0.0
  toast: ^0.1.5
  cloud_firestore: ^0.13.1+1
  shared_preferences: ^0.5.6+1
  image_cropper: ^1.2.1
  youtube_player_flutter: ^6.1.0+4
  firebase_storage: ^3.1.3
  cached_network_image: ^2.0.0
  expandable: ^4.1.3
  barcode_scan_fix: ^1.0.2
  autocomplete_textfield: ^1.7.3
  dropdown_search: ^0.4.4
  connectivity: ^2.0.2
  get: ^3.24.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo_nhealth_horizontal.png
   - assets/images/frame.png
   - assets/images/home_header.png
   - assets/images/icons/manage_patient.png
   - assets/images/icons/register_patient.png
   - assets/images/icons/blood_test.png
   - assets/images/icons/body_measurements.png
   - assets/images/icons/blood_pressure.png
   - assets/images/icons/questionnaire.png
   - assets/images/care_plan.png
   - assets/images/dot_red.png
   - assets/images/icons/blood_test_common.png
   - assets/images/icons/blood_glucose.png
   - assets/images/icons/hba1c.png
   - assets/images/icons/ogtt.png
   - assets/images/icons/smoker.png
   - assets/images/icons/alcohol.png
   - assets/images/icons/fruit.png
   - assets/images/icons/vegetables.png
   - assets/images/icons/activity.png
   - assets/images/icons/height.png
   - assets/images/icons/weight.png
   - assets/images/icons/hip.png
   - assets/images/icons/home.png
   - assets/images/bg_home.png
   - assets/images/work_list_1.png
   - assets/images/work_list_2.png
   - assets/images/icons/icon_alcohol.png
   - assets/images/icons/icon_fruits.png
   - assets/images/icons/icon_physical-activity.png
   - assets/images/icons/icon_smoker.png
   - assets/images/avatar.png
   - assets/images/patient_big.png
   - assets/images/icons/well.png
   - assets/images/icons/unwell.png
   - assets/images/icons/unwell_green.png
   - assets/images/icons/unwell_red.png
   - assets/images/icons/inventory.png
   - assets/images/user_placeholder.png
   - lang/en.json
   - lang/bn.json

   - assets/medications.json
   - assets/allergies.json
   - assets/districts.json
   - assets/upazilas.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 100
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 300
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 500
        - asset: fonts/Roboto-Black.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
